language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
ignore:
  *.md
deploy:
  provider: surge
  skip_cleanup: true
  domain: praktice-slot-allotment.surge.sh/
  project: ./build/
on:
  branch: master